version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: "direct"
    labels:
      - 'node dependencies'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
    open-pull-requests-limit: 10
    labels:
      - 'github-actions dependencies'
