import { memo } from "react"

import { Typography, Container } from "@mui/material"
import type { NextPage } from "next"
import Head from "next/head"

import Footer from "@components/Footer"

const Home: NextPage = () => (
  <>
    <Head>
      <title>Conference</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Container
      component="main"
      maxWidth="sm"
    >
      <Typography variant="h1">
        Welcome to Conference !
      </Typography>
    </Container>

    <Footer />
  </>
)

export default memo(Home)
